import React from 'react';
import { motion } from 'motion/react';
import { Scale, FileCheck, AlertCircle } from 'lucide-react';

export const TermsOfService: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-[#0f172a] text-white p-8">
      <div className="max-w-4xl mx-auto">
        <button 
          onClick={onBack}
          className="mb-8 text-accent hover:underline flex items-center"
        >
          &larr; Back to Home
        </button>
        
        <div className="glass-panel p-10 rounded-3xl">
          <div className="flex items-center space-x-3 mb-8">
            <Scale className="w-8 h-8 text-accent" />
            <h1 className="text-3xl font-bold">Terms of Service</h1>
          </div>

          <div className="prose prose-invert max-w-none text-white/70 space-y-6">
            <p className="text-sm italic">Last Updated: May 2026</p>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using Local Seo Machine, you agree to be bound by these Terms of Service. If you do not agree to all of these terms, do not use our services.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">2. Service Description</h2>
              <p>Local Seo Machine provides AI-powered content generation tools designed to assist in local search engine optimization. We provide these tools "as is" and do not guarantee specific ranking results or traffic increases.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">3. User Responsibilities</h2>
              <p>Users are responsible for verifying the accuracy of the content generated by the AI. We are not liable for any incorrect information, legal issues, or SEO penalties resulting from the use of generated content.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">4. Subscriptions and Payments</h2>
              <p>Pro subscriptions are billed on a recurring basis. You may cancel at any time, but we do not offer refunds for partial billing periods unless required by law.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">5. Limitation of Liability</h2>
              <p>In no event shall Local Seo Machine or its creators be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the platform.</p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
};
